-- Profile Data
INSERT INTO profile (id, full_name, title, bio, profile_image_url, email, phone, location, linkedin_url, github_url, website_url)
VALUES (1, 'Vishwash Khandal', 'Senior Software Engineer', 'Senior Software Engineer with 4+ years of experience in designing, developing, and implementing software applications. Ability to collaborate with cross-functional teams, gather requirements, & deliver innovative solutions. Skilled in Java and Spring, with expertise in microservices, distributed systems, performance-focused design, and modern development practices.', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face&auto=format&q=80', 'vishwash.khandal@example.com', '+91-9876543210', 'Mumbai, India', 'https://linkedin.com/in/vishwash-khandal-345b66165', 'https://github.com/vishwashkhandal', 'https://vishwashkhandal.dev');

-- Skills Data
INSERT INTO skill (name, category, icon_url, proficiency, description) VALUES
('Java/J2EE', 'Backend', 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg', 95, 'Expert in Java and J2EE development with Spring ecosystem'),
('Spring/JPA/Hibernate', 'Backend', 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/spring/spring-original.svg', 90, 'Spring Framework, JPA, Hibernate for data persistence'),
('JUnit/Mockito', 'Testing', 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/junit/junit-plain.svg', 85, 'Unit testing with JUnit and Mockito'),
('OOAD/OOPS', 'Design', 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg', 90, 'Object-Oriented Analysis and Design principles'),
('SQL- Oracle DB', 'Database', 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/oracle/oracle-original.svg', 85, 'Oracle Database with advanced SQL queries'),
('NoSQL- Aerospike', 'Database', 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redis/redis-original.svg', 80, 'Aerospike NoSQL database operations'),
('React.js/Node.js', 'Frontend', 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg', 85, 'React.js and Node.js for full-stack development'),
('HTML/CSS/JavaScript', 'Frontend', 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg', 90, 'Modern HTML5, CSS3, and JavaScript development'),
('DSA/System Design', 'Design', 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg', 85, 'Data Structures, Algorithms, and System Design'),
('Message Queues', 'Infrastructure', 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/apachekafka/apachekafka-original.svg', 80, 'Kafka and message queue implementations'),
('GitLab/GitHub/Git', 'Tools', 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg', 90, 'Version control with Git, GitLab, and GitHub'),
('Docker/Kubernetes', 'DevOps', 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg', 85, 'Containerization with Docker and orchestration with Kubernetes'),
('REST APIs', 'Backend', 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/spring/spring-original.svg', 90, 'RESTful API design and development'),
('SOAP/XML/JSON', 'Integration', 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/xml/xml-plain.svg', 85, 'SOAP services, XML, and JSON data handling'),
('Tomcat/Kafka/Redis', 'Infrastructure', 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/apache/apache-original.svg', 80, 'Tomcat server, Kafka messaging, Redis caching'),
('Unix/Linux/GenAI', 'Tools', 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg', 85, 'Unix/Linux systems and Generative AI tools'),
('Jira/Confluence', 'Tools', 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jira/jira-original.svg', 80, 'Project management with Jira and Confluence'),
('Agile (Scrum)/Jira', 'Methodology', 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jira/jira-original.svg', 90, 'Agile Scrum methodology implementation'),
('Grafana/Prometheus', 'Monitoring', 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/grafana/grafana-original.svg', 75, 'Application monitoring with Grafana and Prometheus'),
('Maven/CI-CD/Jenkins', 'DevOps', 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/maven/maven-original.svg', 85, 'Build automation with Maven and CI/CD with Jenkins');

-- Projects Data
INSERT INTO project (name, description, image_url, github_url, live_url, technologies, created_at, featured) VALUES
('Biller Networks Microservices', 'Microservices responsible for recharge & bill fetch/payment using Java, spring boot, TDD, JOSE, OAuth, Kafka, Grafana, Prometheus, CI/CD. Features include transaction processing, secure authentication, real-time monitoring, and automated deployment pipelines.', 'https://via.placeholder.com/600x400', 'https://github.com/vishwashkhandal/biller-networks', 'https://biller-networks-demo.com', 'Java, Spring Boot, Kafka, Grafana, Prometheus, JOSE, OAuth, CI/CD', '2023-01-15', true),
('Card Validation Service', 'Application for credit-card statement validation using Java, JWT, spring boot, maven, Caffeine cache. Implements secure token-based authentication, efficient caching mechanisms, and comprehensive validation logic for financial transactions.', 'https://via.placeholder.com/600x400', 'https://github.com/vishwashkhandal/card-validation', 'https://card-validation-demo.com', 'Java, Spring Boot, JWT, Maven, Caffeine Cache', '2022-08-10', true),
('BBPS Service Migration', 'Migrated BBPS (Bharat Bill Payment System) from active-passive to active-active server architecture using Redis Pub-Sub. Enhanced system performance by 50%, improved high availability, load balancing, and resource utilization.', 'https://via.placeholder.com/600x400', 'https://github.com/vishwashkhandal/bbps-migration', 'https://bbps-migration-demo.com', 'Java, Spring Boot, Redis, Microservices', '2022-05-20', true),
('Biller Connect Application', 'Designed Biller Connect application from scratch for bill/recharge payments. Implemented Kafka for messaging, throttling mechanisms, concurrency/multithreading practices, and caching features to handle 200 TPS.', 'https://via.placeholder.com/600x400', 'https://github.com/vishwashkhandal/biller-connect', 'https://biller-connect-demo.com', 'Java, Spring Boot, Kafka, Redis, Microservices', '2021-12-01', false),
('Simulator Development', 'Developed simulators from scratch that saved over 30% of testing time. Reduced dependency on external microservices, enabled convenient manual client-side testing, and helped developers test changes quickly without external service dependencies.', 'https://via.placeholder.com/600x400', 'https://github.com/vishwashkhandal/simulators', 'https://simulators-demo.com', 'Java, Spring Boot, REST APIs, Testing', '2021-10-15', false);

-- Hobbies Data
INSERT INTO hobby (name, description, image_url, icon_url) VALUES
('Open Source Contribution', 'Active contributor to open source projects, focusing on Java and Spring Boot frameworks. Love sharing knowledge and helping the developer community.', 'https://via.placeholder.com/400x300', '🚀'),
('Technical Blogging', 'Writing technical articles about software development, system design, and best practices. Sharing experiences with microservices, performance optimization, and DevOps.', 'https://via.placeholder.com/400x300', '✍️'),
('Learning & Research', 'Continuous learner exploring new technologies, AI/ML applications, and emerging trends in software development. Always curious about innovative solutions.', 'https://via.placeholder.com/400x300', '🎓'),
('Problem Solving', 'Enjoy solving complex algorithmic challenges and participating in coding competitions. Strong believer in clean code and efficient algorithms.', 'https://via.placeholder.com/400x300', '🧩'),
('Team Mentoring', 'Passionate about guiding junior developers and fostering collaborative team environments. Believe in knowledge sharing and continuous improvement.', 'https://via.placeholder.com/400x300', '👥');

-- Experience Data
INSERT INTO experience (title, company, location, start_date, end_date, current, description, company_logo_url) VALUES
('Software Engineer', 'BillDesk (IndiaIdeas.com Limited)', 'Mumbai, India', DATE '2021-08-01', DATE '2025-10-12', false, 'Led and took ownership of Card Net backend microservices responsible for critical transaction token generation, overseeing the entire process from development to deployment. Delivered rapid microservice development solutions to meet stringent RBI compliance deadlines to nullify critical data and replace with alternate Identifier within 2 weeks timeline. Played a key role in designing Biller Connect application from scratch for bill/recharge payments. Contributed in logic design to enhance scalability and fault tolerance using Kafka along with throttling mechanism, concurrency/multithreading practices, leveraged caching features which enabled the system to handle 200 TPS. Developed and designed simulators from scratch, saved over 30% of testing time, reduced dependency on external microservices, enabled convenient manual client-side testing, and helped developers test their changes quickly without relying on external services. Developed features with Redis Pub-Sub in the BBPS service and migrated the system from an active-passive to an active-active server architecture, enhancing performance by 50%, ensuring high availability, improving load balancing, and optimizing resource utilization. Mentored a team of five members, guiding them through agile methodologies, continuous improvements & stakeholder communication to enhance collaboration and project efficiency. Acted as a key code reviewer, maintaining code quality, applying design patterns, & resolving critical bugs in production deployments through cross-functional team collaboration. Improved application performance by implementing caching and multi-table approaches, streamlining the archiving process, and reducing table read times. Engaged in the entire Software Development Life Cycle, from requirement discussions and proof of concept design to deploying microservices on UAT and production environments. Conducted Coverity scans and VAPT, implemented necessary fixes, coordinated with the support team, and performed live testing with the product team before the final launch.', '/logos/billdesk-logo.svg'),
('Senior Software Engineer', 'Interactive Brokers', 'Mumbai, India', DATE '2025-10-13', NULL, true, 'Leading development initiatives for global trading platforms and financial technology solutions. Working on high-performance, scalable systems handling millions of transactions daily. Contributing to innovative trading technologies, risk management systems, and advanced algorithmic trading platforms. Collaborating with international teams across multiple time zones to deliver cutting-edge financial technology solutions.', '/logos/interactive-brokers-logo.svg');
